In [138]:
import requests
import json

In [139]:
import requests

key = "O4U8xwNQXD93OMUA_6xQBjpN3weIVGU_bee54DlbziSbY8Il_-X1Y4s_-vMkQkjKoZORxT38UQTMhFnCeo6jQMx23wce4RUn2Tchdi-aoInwRTbpqyvMZrieeRzYaXYx"
fulldata = []
offset = 0

while True:
  page = requests.get(f"https://api.yelp.com/v3/businesses/search?location=New York City&limit=40&offset={offset}",
                    headers={"accept": "application/json", "Authorization": f"Bearer {key}"})
  res = page.json()
  print(res)

  if "businesses" in res:
     fulldata += res["businesses"]
  else:
    break

  offset += 40

{'businesses': [{'id': 'zRXMvxUX_rOliKZPpkWi_g', 'alias': 'valerie-new-york', 'name': 'Valerie', 'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/mnH5QFkSMzZgd6P5eSZvvw/o.jpg', 'is_closed': False, 'url': 'https://www.yelp.com/biz/valerie-new-york?adjust_creative=R-Dcfq6HRa0ds32S-gUEaQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=R-Dcfq6HRa0ds32S-gUEaQ', 'review_count': 1378, 'categories': [{'alias': 'newamerican', 'title': 'New American'}, {'alias': 'cocktailbars', 'title': 'Cocktail Bars'}], 'rating': 4.2, 'coordinates': {'latitude': 40.756326, 'longitude': -73.981117}, 'transactions': ['delivery'], 'price': '$$', 'location': {'address1': '45 W 45th St between 5th & 6th Ave', 'address2': '', 'address3': None, 'city': 'New York', 'zip_code': '10036', 'country': 'US', 'state': 'NY', 'display_address': ['45 W 45th St between 5th & 6th Ave', 'New York, NY 10036']}, 'phone': '+12123024545', 'display_phone': '(212) 302-4545', 'distance': 5758.012347666175, 'business_hours': [{'open': [{'is_overnight': False, 'start': '1130', 'end': '0000', 'day': 0}, {'is_overnight': True, 'start': '1130', 'end': '0200', 'day': 1}, {'is_overnight': True, 'start': '1130', 'end': '0200', 'day': 2}, {'is_overnight': True, 'start': '1130', 'end': '0200', 'day': 3}, {'is_overnight': True, 'start': '1130', 'end': '0200', 'day': 4}, {'is_overnight': True, 'start': '1100', 'end': '0200', 'day': 5}, {'is_overnight': False, 'start': '1100', 'end': '0000', 'day': 6}], 'hours_type': 'REGULAR', 'is_open_now': True}], 'attributes': {'business_temp_closed': None, 'menu_url': 'https://www.valerienewyorkcity.com/menus/', 'open24_hours': None, 'waitlist_reservation': None}}, {'id': 'hdiuRS9sVZSMReZm4oV5SA', 'alias': 'da-andrea-greenwich-village-new-york-2', 'name': 'Da Andrea - Greenwich Village', 'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/wKwJc8wF-Crs1M-Ci3NmIA/o.jpg', 'is_closed': False, 'url': 'https://www.yelp.com/biz/da-andrea-greenwich-village-new-york-2?adjust_creative=R-Dcfq6HRa0ds32S-gUEaQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=R-Dcfq6HRa0ds32S-gUEaQ', 'review_count': 2744, 'categories': [{'alias': 'italian', 'title': 'Italian'}, {'alias': 'mediterranean', 'title': 'Mediterranean'}, {'alias': 'breakfast_brunch', 'title': 'Breakfast & Brunch'}], 'rating': 4.4, 'coordinates': {'latitude': 40.736287, 'longitude': -73.995865}, 'transactions': ['delivery', 'restaurant_reservation', 'pickup'], 'price': '$$', 'location': {'address1': '35 W 13th St', 'address2': '', 'address3': '', 'city': 'New York', 'zip_code': '10011', 'country': 'US', 'state': 'NY', 'display_address': ['35 W 13th St', 'New York, NY 10011']}, 'phone': '+12123671979', 'display_phone': '(212) 367-1979', 'distance': 3416.4417433907984, 'business_hours': [{'open': [{'is_overnight': False, 'start': '1130', 'end': '2200', 'day': 0}, {'is_overnight': False, 'start': '1130', 'end': '2200', 'day': 1}, {'is_overnight': False, 'start': '1130', 'end': '2200', 'day': 2}, {'is_overnight': False, 'start': '1130', 'end': '2200', 'day': 3}, {'is_overnight': False, 'start': '1130', 'end': '2300', 'day': 4}, {'is_overnight': False, 'start': '1100', 'end': '2300', 'day': 5}, {'is_overnight': False, 'start': '1100', 'end': '2200', 'day': 6}], 'hours_type': 'REGULAR', 'is_open_now': True}], 'attributes': {'business_temp_closed': None, 'menu_url': 'https://www.daandreanyc.com/menu', 'open24_hours': None, 'waitlist_reservation': True}}, {'id': '16ZnHpuaaBt92XWeJHCC5A', 'alias': 'olio-e-più-new-york-7', 'name': 'Olio e Più', 'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/kolVy0aTZ9vWZ6EG9FjtGw/o.jpg', 'is_closed': False, 'url': 'https://www.yelp.com/biz/olio-e-pi%C3%B9-new-york-7?adjust_creative=R-Dcfq6HRa0ds32S-gUEaQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=R-Dcfq6HRa0ds32S-gUEaQ', 'review_count': 7330, 'categories': [{'alias': 'pizza', 'title': 'Pizza'}, {'alias': 'italian', 'title': 'Italian'}, {'alias': 'cocktailbars', 'title': 'Cocktail Bars'}], 'rating': 4.5, 'coordinates': {'latitude': 40.73406231935954, 'longitude': -73.99999980859876}, 'transactions': ['delivery', 'pickup'], 'price': '$$$', 'location': {'address1': '3 Greenwich Ave', 'address2': None, 'address3': '', 'city': 'New York', 'zip_code': '10014', 'country': 'US', 'state': 'NY', 'display_address': ['3 Greenwich Ave', 'New York, NY 10014']}, 'phone': '+12122436546', 'display_phone': '(212) 243-6546', 'distance': 3207.585573981827, 'business_hours': [{'open': [{'is_overnight': False, 'start': '1100', 'end': '0000', 'day': 0}, {'is_overnight': False, 'start': '1100', 'end': '0000', 'day': 1}, {'is_overnight': False, 'start': '1100', 'end': '0000', 'day': 2}, {'is_overnight': False, 'start': '1100', 'end': '0000', 'day': 3}, {'is_overnight': False, 'start': '1100', 'end': '0000', 'day': 4}, {'is_overnight': False, 'start': '1000', 'end': '0000', 'day': 5}, {'is_overnight': False, 'start': '1000', 'end': '0000', 'day': 6}], 'hours_type': 'REGULAR', 'is_open_now': True}], 'attributes': {'business_temp_closed': None, 'menu_url': 'https://www.olioepiu.com/nyc-menu/', 'open24_hours': None, 'waitlist_reservation': None}}, {'id': 'qY1o1MhoRyN84RRhUJtvpQ', 'alias': 'her-name-is-han-new-york-3', 'name': 'Her Name Is Han', 'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/NhRNYeyuXeOK8h6RepcClA/o.jpg', 'is_closed': False, 'url': 'https://www.yelp.com/biz/her-name-is-han-new-york-3?adjust_creative=R-Dcfq6HRa0ds32S-gUEaQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=R-Dcfq6HRa0ds32S-gUEaQ', 'review_count': 2274, 'categories': [{'alias': 'korean', 'title': 'Korean'}, {'alias': 'breakfast_brunch', 'title': 'Breakfast & Brunch'}], 'rating': 4.3, 'coordinates': {'latitude': 40.74625007940397, 'longitude': -73.98476227403484}, 'transactions': ['delivery', 'pickup'], 'price': '$$', 'location': {'address1': '17 E 31st St', 'address2': '', 'address3': '', 'city': 'New York', 'zip_code': '10016', 'country': 'US', 'state': 'NY', 'display_address': ['17 E 31st St', 'New York, NY 10016']}, 'phone': '+12127799990', 'display_phone': '(212) 779-9990', 'distance': 4596.426098866733, 'business_hours': [{'open': [{'is_overnight': False, 'start': '1200', 'end': '1400', 'day': 0}, {'is_overnight': False, 'start': '1700', 'end': '2145', 'day': 0}, {'is_overnight': False, 'start': '1200', 'end': '1400', 'day': 1}, {'is_overnight': False, 'start': '1700', 'end': '2145', 'day': 1}, {'is_overnight': False, 'start': '1200', 'end': '1400', 'day': 2}, {'is_overnight': False, 'start': '1700', 'end': '2145', 'day': 2}, {'is_overnight': False, 'start': '1200', 'end': '1400', 'day': 3}, {'is_overnight': False, 'start': '1700', 'end': '2145', 'day': 3}, {'is_overnight': False, 'start': '1200', 'end': '1400', 'day': 4}, {'is_overnight': False, 'start': '1700', 'end': '2245', 'day': 4}, {'is_overnight': False, 'start': '1200', 'end': '1400', 'day': 5}, {'is_overnight': False, 'start': '1700', 'end': '2245', 'day': 5}, {'is_overnight': False, 'start': '1200', 'end': '1400', 'day': 6}, {'is_overnight': False, 'start': '1700', 'end': '2145', 'day': 6}], 'hours_type': 'REGULAR', 'is_open_now': True}], 'attributes': {'business_temp_closed': None, 'menu_url': '', 'open24_hours': None, 'waitlist_reservation': None}}, {'id': 'ysqgdbSrezXgVwER2kQWKA', 'alias': 'julianas-brooklyn-3', 'name': "Juliana's", 'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/od36nFW220aMFAnNP00ocw/o.jpg', 'is_closed': False, 'url': 'https://www.yelp.com/biz/julianas-brooklyn-3?adjust_creative=R-Dcfq6HRa0ds32S-gUEaQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=R-Dcfq6HRa0ds32S-gUEaQ', 'review_count': 2969, 'categories': [{'alias': 'pizza', 'title': 'Pizza'}], 'rating': 4.4, 'coordinates': {'latitude': 40.70274718768062, 'longitude': -73.99343490196397}, 'transactions': ['delivery'], 'price': '$$', 'location': {'address1': '19 Old Fulton St', 'address2': '', 'address3': '', 'city': 'Brooklyn', 'zip_code': '11201', 'country': 'US', 'state': 'NY', 'display_address': ['19 Old Fulton St', 'Brooklyn, NY 11201']}, 'phone': '+17185966700', 'display_phone': '(718) 596-6700', 'distance': 318.8762608116642, 'business_hours': [{'open': [{'is_overnight': False, 'start': '1130', 'end': '1515', 'day': 0}, {'is_overnight': False, 'start': '1600', 'end': '2100', 'day': 0}, {'is_overnight': False, 'start': '1130', 'end': '1515', 'day': 1}, {'is_overnight': False, 'start': '1600', 'end': '2100', 'day': 1}, {'is_overnight': False, 'start': '1130', 'end': '1515', 'day': 2}, {'is_overnight': False, 'start': '1600', 'end': '2100', 'day': 2}, {'is_overnight': False, 'start': '1130', 'end': '1515', 'day': 3}, {'is_overnight': False, 'start': '1600', 'end': '2100', 'day': 3}, {'is_overnight': False, 'start': '1130', 'end': '1515', 'day': 4}, {'is_overnight': False, 'start': '1600', 'end': '2100', 'day': 4}, {'is_overnight': False, 'start': '1130', 'end': '1515', 'day': 5}, {'is_overnight': False, 'start': '1600', 'end': '2100', 'day': 5}, {'is_overnight': False, 'start': '1130', 'end': '1515', 'day': 6}, {'is_overnight': False, 'start': '1600', 'end': '2100', 'day': 6}], 'hours_type': 'REGULAR', 'is_open_now': True}], 'attributes': {'business_temp_closed': None, 'menu_url': 'https://julianaspizza.com/menus/', 'open24_hours': None, 'waitlist_reservation': None}}, {'id': '8YWLuLUKj0t_0_Xv06UUtw', 'alias': 'yes-apothecary-new-york-6', 'name': "Ye's Apothecary", 'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/sH_vWL_-1__EcA9tCsehQw/o.jpg', 'is_closed': False, 'url': 'https://www.yelp.com/biz/yes-apothecary-new-york-6?adjust_creative=R-Dcfq6HRa0ds32S-gUEaQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=R-Dcfq6HRa0ds32S-gUEaQ', 'review_count': 1089, 'categories': [{'alias': 'szechuan', 'title': 'Szechuan'}, {'alias': 'speakeasies', 'title': 'Speakeasies'}], 'rating': 4.6, 'coordinates': {'latitude': 40.71945, 'longitude': -73.9898}, 'transactions': [], 'price': '$$', 'location': {'address1': '119 Orchard St', 'address2': None, 'address3': '', 'city': 'New York', 'zip_code': '10002', 'country': 'US', 'state': 'NY', 'display_address': ['119 Orchard St', 'New York, NY 10002']}, 'phone': '+19296552515', 'display_phone': '(929) 655-2515', 'distance': 1591.3798693136603, 'business_hours': [{'open': [{'is_overnight': False, 'start': '1730', 'end': '2330', 'day': 1}, {'is_overnight': False, 'start': '1730', 'end': '2330', 'day': 2}, {'is_overnight': False, 'start': '1730', 'end': '2330', 'day': 3}, {'is_overnight': True, 'start': '1700', 'end': '0100', 'day': 4}, {'is_overnight': True, 'start': '1700', 'end': '0100', 'day': 5}, {'is_overnight': False, 'start': '1300', 'end': '2100', 'day': 6}], 'hours_type': 'REGULAR', 'is_open_now': True}], 'attributes': {'business_temp_closed': None, 'menu_url': 'https://www.yesapothecary.com/menu', 'open24_hours': None, 'waitlist_reservation': True}}, {'id': 'XgiG7K7ubHsj2JJ-c2sXnw', 'alias': 'thai-diner-new-york', 'name': 'Thai Diner', 'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/gQJ2oU3ejDu8RK_2KsV_5g/o.jpg', 'is_closed': False, 'url': 'https://www.yelp.com/biz/thai-diner-new-york?adjust_creative=R-Dcfq6HRa0ds32S-gUEaQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=R-Dcfq6HRa0ds32S-gUEaQ', 'review_count': 1253, 'categories': [{'alias': 'thai', 'title': 'Thai'}], 'rating': 4.2, 'coordinates': {'latitude': 40.72071042964739, 'longitude': -73.9956057}, 'transactions': ['delivery'], 'price': '$$', 'location': {'address1': '186 Mott St', 'address2': None, 'address3': None, 'city': 'New York', 'zip_code': '10012', 'country': 'US', 'state': 'NY', 'display_address': ['186 Mott St', 'New York, NY 10012']}, 'phone': '+16465594140', 'display_phone': '(646) 559-4140', 'distance': 1690.0745598587491, 'business_hours': [{'open': [{'is_overnight': False, 'start': '0830', 'end': '2230', 'day': 0}, {'is_overnight': False, 'start': '0830', 'end': '2230', 'day': 1}, {'is_overnight': False, 'start': '0830', 'end': '2230', 'day': 2}, {'is_overnight': False, 'start': '0830', 'end': '2330', 'day': 3}, {'is_overnight': False, 'start': '0830', 'end': '2330', 'day': 4}, {'is_overnight': False, 'start': '1000', 'end': '2330', 'day': 5}, {'is_overnight': False, 'start': '1000', 'end': '2230', 'day': 6}], 'hours_type': 'REGULAR', 'is_open_now': True}], 'attributes': {'business_temp_closed': None, 'menu_url': 'https://www.thaidiner.com/menu-3221', 'open24_hours': None, 'waitlist_reservation': None}}, {'id': 'qBGKigOGn_flCx1apxPzlA', 'alias': 'piccola-cucina-osteria-new-york-2', 'name': 'Piccola Cucina Osteria', 'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/YK-z93eYuueWrApOHDcFaQ/o.jpg', 'is_closed': False, 'url': 'https://www.yelp.com/biz/piccola-cucina-osteria-new-york-2?adjust_creative=R-Dcfq6HRa0ds32S-gUEaQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=R-Dcfq6HRa0ds32S-gUEaQ', 'review_count': 933, 'categories': [{'alias': 'italian', 'title': 'Italian'}], 'rating': 4.3, 'coordinates': {'latitude': 40.72503127956934, 'longitude': -74.0032820972858}, 'transactions': ['delivery', 'pickup'], 'price': '$$', 'location': {'address1': '196 Spring St', 'address2': '', 'address3': '', 'city': 'New York', 'zip_code': '10012', 'country': 'US', 'state': 'NY', 'display_address': ['196 Spring St', 'New York, NY 10012']}, 'phone': '+16464787488', 'display_phone': '(646) 478-7488', 'distance': 2296.1994293335506, 'business_hours': [{'open': [{'is_overnight': False, 'start': '1130', 'end': '2300', 'day': 0}, {'is_overnight': False, 'start': '1130', 'end': '2300', 'day': 1}, {'is_overnight': False, 'start': '1130', 'end': '2300', 'day': 2}, {'is_overnight': False, 'start': '1130', 'end': '2300', 'day': 3}, {'is_overnight': False, 'start': '1130', 'end': '2300', 'day': 4}, {'is_overnight': False, 'start': '1130', 'end': '2300', 'day': 5}, {'is_overnight': False, 'start': '1130', 'end': '2300', 'day': 6}], 'hours_type': 'REGULAR', 'is_open_now': True}], 'attributes': {'business_temp_closed': None, 'menu_url': 'https://www.piccolacucinagroup.com/wp-content/uploads/2021/11/menu-piccola-cucina-osteria-spring-nyc-ott2021.pdf', 'open24_hours': None, 'waitlist_reservation': None}}, {'id': 'MphfKkYFEe0BDQ6hZ0A5fA', 'alias': 'gelso-and-grand-new-york', 'name': 'Gelso & Grand', 'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/eUVbVwSUhPl0K8YE7nrUBw/o.jpg', 'is_closed': False, 'url': 'https://www.yelp.com/biz/gelso-and-grand-new-york?adjust_creative=R-Dcfq6HRa0ds32S-gUEaQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=R-Dcfq6HRa0ds32S-gUEaQ', 'review_count': 1671, 'categories': [{'alias': 'italian', 'title': 'Italian'}, {'alias': 'pastashops', 'title': 'Pasta Shops'}, {'alias': 'pizza', 'title': 'Pizza'}], 'rating': 4.3, 'coordinates': {'latitude': 40.71958, 'longitude': -73.99734}, 'transactions': ['delivery', 'pickup'], 'price': '$$', 'location': {'address1': '186 Grand St', 'address2': '', 'address3': '', 'city': 'New York', 'zip_code': '10013', 'country': 'US', 'state': 'NY', 'display_address': ['186 Grand St', 'New York, NY 10013']}, 'phone': '+12122261600', 'display_phone': '(212) 226-1600', 'distance': 1583.0802664491484, 'business_hours': [{'open': [{'is_overnight': False, 'start': '1100', 'end': '2300', 'day': 0}, {'is_overnight': False, 'start': '1100', 'end': '2300', 'day': 1}, {'is_overnight': False, 'start': '1100', 'end': '2300', 'day': 2}, {'is_overnight': False, 'start': '1100', 'end': '2300', 'day': 3}, {'is_overnight': False, 'start': '1000', 'end': '0000', 'day': 4}, {'is_overnight': False, 'start': '1000', 'end': '0000', 'day': 5}, {'is_overnight': False, 'start': '1000', 'end': '2300', 'day': 6}], 'hours_type': 'REGULAR', 'is_open_now': True}], 'attributes': {'business_temp_closed': None, 'menu_url': 'https://www.gelsoandgrand.com/menu', 'open24_hours': None, 'waitlist_reservation': None}}, {'id': 'xTwzk3lh7tE2GFiVQop1kg', 'alias': 'nubiani-new-york', 'name': 'Nubiani', 'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/XROeL25znJpf2sCB2wyXCA/o.jpg', 'is_closed': False, 'url': 'https://www.yelp.com/biz/nubiani-new-york?adjust_creative=R-Dcfq6HRa0ds32S-gUEaQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=R-Dcfq6HRa0ds32S-gUEaQ', 'review_count': 509, 'categories': [{'alias': 'korean', 'title': 'Korean'}, {'alias': 'bbq', 'title': 'Barbeque'}], 'rating': 4.5, 'coordinates': {'latitude': 40.74700575561414, 'longitude': -73.9854169149663}, 'transactions': ['delivery', 'pickup'], 'location': {'address1': '315 5th Ave', 'address2': 'Fl 3', 'address3': '', 'city': 'New York', 'zip_code': '10016', 'country': 'US', 'state': 'NY', 'display_address': ['315 5th Ave', 'Fl 3', 'New York, NY 10016']}, 'phone': '+19176230807', 'display_phone': '(917) 623-0807', 'distance': 4670.068302268334, 'business_hours': [{'open': [{'is_overnight': False, 'start': '1200', 'end': '2300', 'day': 0}, {'is_overnight': False, 'start': '1200', 'end': '2300', 'day': 1}, {'is_overnight': False, 'start': '1200', 'end': '2300', 'day': 2}, {'is_overnight': False, 'start': '1200', 'end': '0000', 'day': 3}, {'is_overnight': True, 'start': '1200', 'end': '0100', 'day': 4}, {'is_overnight': True, 'start': '1200', 'end': '0100', 'day': 5}, {'is_overnight': False, 'start': '1200', 'end': '2300', 'day': 6}], 'hours_type': 'REGULAR', 'is_open_now': True}], 'attributes': {'business_temp_closed': None, 'menu_url': 'https://www.nubianinyc.com/menu', 'open24_hours': None, 'waitlist_reservation': None}}, {'id': '7_hGsGEkHrjgAiYVjrCFnw', 'alias': 'carbone-new-york', 'name': 'Carbone', 'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/IRI1wEHK90gS5PB9-alWDA/o.jpg', 'is_closed': False, 'url': 'https://www.yelp.com/biz/carbone-new-york?adjust_creative=R-Dcfq6HRa0ds32S-gUEaQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=R-Dcfq6HRa0ds32S-gUEaQ', 'review_count': 2082, 'categories': [{'alias': 'italian', 'title': 'Italian'}], 'rating': 4.0, 'coordinates': {'latitude': 40.72800126711089, 'longitude': -74.00024274442806}, 'transactions': [], 'price': '$$$$', 'location': {'address1': '181 Thompson St', 'address2': '', 'address3': '', 'city': 'New York', 'zip_code': '10012', 'country': 'US', 'state': 'NY', 'display_address': ['181 Thompson St', 'New York, NY 10012']}, 'phone': '+12122543000', 'display_phone': '(212) 254-3000', 'distance': 2547.331717119722, 'business_hours': [{'open': [{'is_overnight': False, 'start': '1700', 'end': '2330', 'day': 0}, {'is_overnight': False, 'start': '1130', 'end': '1400', 'day': 1}, {'is_overnight': False, 'start': '1700', 'end': '2330', 'day': 1}, {'is_overnight': False, 'start': '1130', 'end': '1400', 'day': 2}, {'is_overnight': False, 'start': '1700', 'end': '2330', 'day': 2}, {'is_overnight': False, 'start': '1130', 'end': '1400', 'day': 3}, {'is_overnight': False, 'start': '1700', 'end': '2330', 'day': 3}, {'is_overnight': False, 'start': '1130', 'end': '1400', 'day': 4}, {'is_overnight': False, 'start': '1700', 'end': '2330', 'day': 4}, {'is_overnight': False, 'start': '1130', 'end': '1400', 'day': 5}, {'is_overnight': False, 'start': '1700', 'end': '2330', 'day': 5}, {'is_overnight': False, 'start': '1130', 'end': '1400', 'day': 6}, {'is_overnight': False, 'start': '1700', 'end': '2330', 'day': 6}], 'hours_type': 'REGULAR', 'is_open_now': True}], 'attributes': {'business_temp_closed': None, 'menu_url': 'http://carbonenewyork.com/menus.php', 'open24_hours': None, 'waitlist_reservation': None}}, {'id': '9fG8-RRh1rzuCKN2TmF-QQ', 'alias': '5ive-spice-new-york-2', 'name': '5ive Spice', 'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/-wN4V3HQZBorFWzESdzdUA/o.jpg', 'is_closed': False, 'url': 'https://www.yelp.com/biz/5ive-spice-new-york-2?adjust_creative=R-Dcfq6HRa0ds32S-gUEaQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=R-Dcfq6HRa0ds32S-gUEaQ', 'review_count': 964, 'categories': [{'alias': 'vietnamese', 'title': 'Vietnames

In [140]:
import pandas as pd

In [141]:

data = pd.DataFrame(fulldata)
data

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance,business_hours,attributes
0,zRXMvxUX_rOliKZPpkWi_g,valerie-new-york,Valerie,https://s3-media0.fl.yelpcdn.com/bphoto/mnH5QF...,False,https://www.yelp.com/biz/valerie-new-york?adju...,1378,"[{'alias': 'newamerican', 'title': 'New Americ...",4.2,"{'latitude': 40.756326, 'longitude': -73.981117}",[delivery],$$,{'address1': '45 W 45th St between 5th & 6th A...,+12123024545,(212) 302-4545,5758.012348,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
1,hdiuRS9sVZSMReZm4oV5SA,da-andrea-greenwich-village-new-york-2,Da Andrea - Greenwich Village,https://s3-media0.fl.yelpcdn.com/bphoto/wKwJc8...,False,https://www.yelp.com/biz/da-andrea-greenwich-v...,2744,"[{'alias': 'italian', 'title': 'Italian'}, {'a...",4.4,"{'latitude': 40.736287, 'longitude': -73.995865}","[delivery, restaurant_reservation, pickup]",$$,"{'address1': '35 W 13th St', 'address2': '', '...",+12123671979,(212) 367-1979,3416.441743,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
2,16ZnHpuaaBt92XWeJHCC5A,olio-e-più-new-york-7,Olio e Più,https://s3-media0.fl.yelpcdn.com/bphoto/kolVy0...,False,https://www.yelp.com/biz/olio-e-pi%C3%B9-new-y...,7330,"[{'alias': 'pizza', 'title': 'Pizza'}, {'alias...",4.5,"{'latitude': 40.73406231935954, 'longitude': -...","[delivery, pickup]",$$$,"{'address1': '3 Greenwich Ave', 'address2': No...",+12122436546,(212) 243-6546,3207.585574,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
3,qY1o1MhoRyN84RRhUJtvpQ,her-name-is-han-new-york-3,Her Name Is Han,https://s3-media0.fl.yelpcdn.com/bphoto/NhRNYe...,False,https://www.yelp.com/biz/her-name-is-han-new-y...,2274,"[{'alias': 'korean', 'title': 'Korean'}, {'ali...",4.3,"{'latitude': 40.74625007940397, 'longitude': -...","[delivery, pickup]",$$,"{'address1': '17 E 31st St', 'address2': '', '...",+12127799990,(212) 779-9990,4596.426099,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': '',..."
4,ysqgdbSrezXgVwER2kQWKA,julianas-brooklyn-3,Juliana's,https://s3-media0.fl.yelpcdn.com/bphoto/od36nF...,False,https://www.yelp.com/biz/julianas-brooklyn-3?a...,2969,"[{'alias': 'pizza', 'title': 'Pizza'}]",4.4,"{'latitude': 40.70274718768062, 'longitude': -...",[delivery],$$,"{'address1': '19 Old Fulton St', 'address2': '...",+17185966700,(718) 596-6700,318.876261,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,1dXX0xXyr99Syd_ZRXwhiA,sushi-lin-upper-west-side-new-york-5,Sushi Lin Upper West Side,https://s3-media0.fl.yelpcdn.com/bphoto/wgH92N...,False,https://www.yelp.com/biz/sushi-lin-upper-west-...,22,"[{'alias': 'japanese', 'title': 'Japanese'}, {...",4.7,"{'latitude': 40.77607632837811, 'longitude': -...","[delivery, pickup]",NaN,"{'address1': '170 Amsterdam Ave', 'address2': ...",+12128842006,(212) 884-2006,7892.084030,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': Non..."
236,X7PpqZZAMBhtmzeUvzfa5g,musaafer-new-york,Musaafer,https://s3-media0.fl.yelpcdn.com/bphoto/6pk5W-...,False,https://www.yelp.com/biz/musaafer-new-york?adj...,106,"[{'alias': 'indpak', 'title': 'Indian'}]",4.2,"{'latitude': 40.71633827608144, 'longitude': -...",[],$$$,"{'address1': '133 Duane St', 'address2': None,...",,,1641.874674,[],"{'business_temp_closed': None, 'menu_url': Non..."
237,hU1ajPmHi-kU6iNbowoEZg,estiatorio-milos-new-york-3,Estiatorio Milos,https://s3-media0.fl.yelpcdn.com/bphoto/qPt0jk...,False,https://www.yelp.com/biz/estiatorio-milos-new-...,410,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",3.9,"{'latitude': 40.7538637135583, 'longitude': -7...","[delivery, pickup]",$$$,"{'address1': '20 Hudson Yards', 'address2': 'F...",+16469071970,(646) 907-1970,5403.338021,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
238,6ARc7vXHWIyqndhQO81XVw,oresh-new-york,Or'esh,https://s3-media0.fl.yelpcdn.com/bphoto/RaD8Ym...,False,https://www.yelp.com/biz/oresh-new-york?adjust...,9,"[{'alias': 'mediterranean', 'title': 'Mediterr...",4.3,"{'latitude': 40.72603, 'longitude': -74.00092}",[],NaN,"{'address1': '450 W Broadway', 'address2': Non...",+12122928999,(212) 292-8999,2341.935174,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
239,2RbBg1CIxBZAc2MQPdxkcA,lillies-victorian-establishment-new-york,Lillie's Victorian Establishment,https://s3-media0.fl.yelpcdn.com/bphoto/akQD2I...,False,https://www.yelp.com/biz/lillies-victorian-est...,1390,"[{'alias': 'bars', 'title': 'Bars'}, {'alias':...",3.7,"{'latitude': 40.737661, 'longitude': -73.991113}","[delivery, pickup]",$$,"{'address1': '13 E 17th St', 'address2': '', '...",+12123371970,(212) 337-1970,3580.953621,"[{'open': [{'is_overnight': True, 'start': '14...","{'business_temp_closed': None, 'menu_url': 'ht..."

In [142]:
data["id"].unique().shape

(234,)

In [143]:
data = data.drop_duplicates("id").reset_index()
data

,index,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance,business_hours,attributes
0,0,zRXMvxUX_rOliKZPpkWi_g,valerie-new-york,Valerie,https://s3-media0.fl.yelpcdn.com/bphoto/mnH5QF...,False,https://www.yelp.com/biz/valerie-new-york?adju...,1378,"[{'alias': 'newamerican', 'title': 'New Americ...",4.2,"{'latitude': 40.756326, 'longitude': -73.981117}",[delivery],$$,{'address1': '45 W 45th St between 5th & 6th A...,+12123024545,(212) 302-4545,5758.012348,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
1,1,hdiuRS9sVZSMReZm4oV5SA,da-andrea-greenwich-village-new-york-2,Da Andrea - Greenwich Village,https://s3-media0.fl.yelpcdn.com/bphoto/wKwJc8...,False,https://www.yelp.com/biz/da-andrea-greenwich-v...,2744,"[{'alias': 'italian', 'title': 'Italian'}, {'a...",4.4,"{'latitude': 40.736287, 'longitude': -73.995865}","[delivery, restaurant_reservation, pickup]",$$,"{'address1': '35 W 13th St', 'address2': '', '...",+12123671979,(212) 367-1979,3416.441743,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
2,2,16ZnHpuaaBt92XWeJHCC5A,olio-e-più-new-york-7,Olio e Più,https://s3-media0.fl.yelpcdn.com/bphoto/kolVy0...,False,https://www.yelp.com/biz/olio-e-pi%C3%B9-new-y...,7330,"[{'alias': 'pizza', 'title': 'Pizza'}, {'alias...",4.5,"{'latitude': 40.73406231935954, 'longitude': -...","[delivery, pickup]",$$$,"{'address1': '3 Greenwich Ave', 'address2': No...",+12122436546,(212) 243-6546,3207.585574,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
3,3,qY1o1MhoRyN84RRhUJtvpQ,her-name-is-han-new-york-3,Her Name Is Han,https://s3-media0.fl.yelpcdn.com/bphoto/NhRNYe...,False,https://www.yelp.com/biz/her-name-is-han-new-y...,2274,"[{'alias': 'korean', 'title': 'Korean'}, {'ali...",4.3,"{'latitude': 40.74625007940397, 'longitude': -...","[delivery, pickup]",$$,"{'address1': '17 E 31st St', 'address2': '', '...",+12127799990,(212) 779-9990,4596.426099,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': '',..."
4,4,ysqgdbSrezXgVwER2kQWKA,julianas-brooklyn-3,Juliana's,https://s3-media0.fl.yelpcdn.com/bphoto/od36nF...,False,https://www.yelp.com/biz/julianas-brooklyn-3?a...,2969,"[{'alias': 'pizza', 'title': 'Pizza'}]",4.4,"{'latitude': 40.70274718768062, 'longitude': -...",[delivery],$$,"{'address1': '19 Old Fulton St', 'address2': '...",+17185966700,(718) 596-6700,318.876261,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,235,1dXX0xXyr99Syd_ZRXwhiA,sushi-lin-upper-west-side-new-york-5,Sushi Lin Upper West Side,https://s3-media0.fl.yelpcdn.com/bphoto/wgH92N...,False,https://www.yelp.com/biz/sushi-lin-upper-west-...,22,"[{'alias': 'japanese', 'title': 'Japanese'}, {...",4.7,"{'latitude': 40.77607632837811, 'longitude': -...","[delivery, pickup]",NaN,"{'address1': '170 Amsterdam Ave', 'address2': ...",+12128842006,(212) 884-2006,7892.084030,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': Non..."
230,236,X7PpqZZAMBhtmzeUvzfa5g,musaafer-new-york,Musaafer,https://s3-media0.fl.yelpcdn.com/bphoto/6pk5W-...,False,https://www.yelp.com/biz/musaafer-new-york?adj...,106,"[{'alias': 'indpak', 'title': 'Indian'}]",4.2,"{'latitude': 40.71633827608144, 'longitude': -...",[],$$$,"{'address1': '133 Duane St', 'address2': None,...",,,1641.874674,[],"{'business_temp_closed': None, 'menu_url': Non..."
231,237,hU1ajPmHi-kU6iNbowoEZg,estiatorio-milos-new-york-3,Estiatorio Milos,https://s3-media0.fl.yelpcdn.com/bphoto/qPt0jk...,False,https://www.yelp.com/biz/estiatorio-milos-new-...,410,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",3.9,"{'latitude': 40.7538637135583, 'longitude': -7...","[delivery, pickup]",$$$,"{'address1': '20 Hudson Yards', 'address2': 'F...",+16469071970,(646) 907-1970,5403.338021,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
232,238,6ARc7vXHWIyqndhQO81XVw,oresh-new-york,Or'esh,https://s3-media0.fl.yelpcdn.com/bphoto/RaD8Ym...,False,https://www.yelp.com/biz/oresh-new-york?adjust...,9,"[{'alias': 'mediterranean', 'title': 'Mediterr...",4.3,"{'latitude': 40.72603, 'longitude': -74.00092}",[],NaN,"{'address1': '450 W Broadway', 'address2': Non...",+12122928999,(212) 292-8999,2341.935174,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
233,239,2RbBg1CIxBZAc2MQPdxkcA,lillies-victorian-establishment-new-york,Lillie's Victorian Establishment,https://s3-media0.fl.yelpcdn.com/bphoto/akQD2I...,False,https://www.yelp.com/biz/lillies-victorian-est...,1390,"[{'alias': 'bars', 'title': 'Bars'}, {'alias':...",3.7,"{'latitude': 40.737661, 'longitude': -73.991113}","[delivery, pickup]",$$,"{'address1': '13 E 17th St', 'address2': '', '...",+12123371970,(212) 337-1970,3580.953621,"[{'open': [{'is_overnight': True, 'start': '14...","{'business_temp_closed': None, 'menu_url': 'ht..."

In [144]:
data = data[["id", "name", "is_closed", "review_count", "categories", "rating", "transactions", "price"]]

In [145]:
transactions_ohe = pd.get_dummies(data["transactions"].explode(), "transactions").groupby(level=0).sum()

In [146]:
data = pd.concat([data, transactions_ohe], axis=1)
data

,id,name,is_closed,review_count,categories,rating,transactions,price,transactions_delivery,transactions_pickup,transactions_restaurant_reservation
0,zRXMvxUX_rOliKZPpkWi_g,Valerie,False,1378,"[{'alias': 'newamerican', 'title': 'New Americ...",4.2,[delivery],$$,1,0,0
1,hdiuRS9sVZSMReZm4oV5SA,Da Andrea - Greenwich Village,False,2744,"[{'alias': 'italian', 'title': 'Italian'}, {'a...",4.4,"[delivery, restaurant_reservation, pickup]",$$,1,1,1
2,16ZnHpuaaBt92XWeJHCC5A,Olio e Più,False,7330,"[{'alias': 'pizza', 'title': 'Pizza'}, {'alias...",4.5,"[delivery, pickup]",$$$,1,1,0
3,qY1o1MhoRyN84RRhUJtvpQ,Her Name Is Han,False,2274,"[{'alias': 'korean', 'title': 'Korean'}, {'ali...",4.3,"[delivery, pickup]",$$,1,1,0
4,ysqgdbSrezXgVwER2kQWKA,Juliana's,False,2969,"[{'alias': 'pizza', 'title': 'Pizza'}]",4.4,[delivery],$$,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
229,1dXX0xXyr99Syd_ZRXwhiA,Sushi Lin Upper West Side,False,22,"[{'alias': 'japanese', 'title': 'Japanese'}, {...",4.7,"[delivery, pickup]",NaN,1,1,0
230,X7PpqZZAMBhtmzeUvzfa5g,Musaafer,False,106,"[{'alias': 'indpak', 'title': 'Indian'}]",4.2,[],$$$,0,0,0
231,hU1ajPmHi-kU6iNbowoEZg,Estiatorio Milos,False,410,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",3.9,"[delivery, pickup]",$$$,1,1,0
232,6ARc7vXHWIyqndhQO81XVw,Or'esh,False,9,"[{'alias': 'mediterranean', 'title': 'Mediterr...",4.3,[],NaN,0,0,0
233,2RbBg1CIxBZAc2MQPdxkcA,Lillie's Victorian Establishment,False,1390,"[{'alias': 'bars', 'title': 'Bars'}, {'alias':...",3.7,"[delivery, pickup]",$$,1,1,0

In [147]:
data["categories"] = data["categories"].apply(lambda x: [y["title"] for y in x])

In [148]:
categories_ohe = pd.get_dummies(data["categories"].explode(), "categories").groupby(level=0).sum()
data = pd.concat([data, categories_ohe], axis=1)
data

,id,name,is_closed,review_count,categories,rating,transactions,price,transactions_delivery,transactions_pickup,...,categories_Tiki Bars,categories_Turkish,categories_Tuscan,categories_Uzbek,categories_Vegan,categories_Venezuelan,categories_Venues & Event Spaces,categories_Vietnamese,categories_Wine Bars,categories_Wraps
0,zRXMvxUX_rOliKZPpkWi_g,Valerie,False,1378,"[New American, Cocktail Bars]",4.2,[delivery],$$,1,0,...,0,0,0,0,0,0,0,0,0,0
1,hdiuRS9sVZSMReZm4oV5SA,Da Andrea - Greenwich Village,False,2744,"[Italian, Mediterranean, Breakfast & Brunch]",4.4,"[delivery, restaurant_reservation, pickup]",$$,1,1,...,0,0,0,0,0,0,0,0,0,0
2,16ZnHpuaaBt92XWeJHCC5A,Olio e Più,False,7330,"[Pizza, Italian, Cocktail Bars]",4.5,"[delivery, pickup]",$$$,1,1,...,0,0,0,0,0,0,0,0,0,0
3,qY1o1MhoRyN84RRhUJtvpQ,Her Name Is Han,False,2274,"[Korean, Breakfast & Brunch]",4.3,"[delivery, pickup]",$$,1,1,...,0,0,0,0,0,0,0,0,0,0
4,ysqgdbSrezXgVwER2kQWKA,Juliana's,False,2969,[Pizza],4.4,[delivery],$$,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,1dXX0xXyr99Syd_ZRXwhiA,Sushi Lin Upper West Side,False,22,"[Japanese, Sushi Bars, Seafood]",4.7,"[delivery, pickup]",NaN,1,1,...,0,0,0,0,0,0,0,0,0,0
230,X7PpqZZAMBhtmzeUvzfa5g,Musaafer,False,106,[Indian],4.2,[],$$$,0,0,...,0,0,0,0,0,0,0,0,0,0
231,hU1ajPmHi-kU6iNbowoEZg,Estiatorio Milos,False,410,"[Seafood, Greek, Mediterranean]",3.9,"[delivery, pickup]",$$$,1,1,...,0,0,0,0,0,0,0,0,0,0
232,6ARc7vXHWIyqndhQO81XVw,Or'esh,False,9,"[Mediterranean, Beer Bar, Cocktail Bars]",4.3,[],NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
233,2RbBg1CIxBZAc2MQPdxkcA,Lillie's Victorian Establishment,False,1390,"[Bars, British, Gastropubs]",3.7,"[delivery, pickup]",$$,1,1,...,0,0,0,0,0,0,0,0,0,0

In [151]:
price_ohe = pd.get_dummies(data["price"])
data = pd.concat([data, price_ohe], axis=1)

In [152]:
data

,id,name,is_closed,review_count,categories,rating,transactions,price,transactions_delivery,transactions_pickup,...,categories_Vegan,categories_Venezuelan,categories_Venues & Event Spaces,categories_Vietnamese,categories_Wine Bars,categories_Wraps,$,$$,$$$,$$$$
0,zRXMvxUX_rOliKZPpkWi_g,Valerie,False,1378,"[New American, Cocktail Bars]",4.2,[delivery],$$,1,0,...,0,0,0,0,0,0,False,True,False,False
1,hdiuRS9sVZSMReZm4oV5SA,Da Andrea - Greenwich Village,False,2744,"[Italian, Mediterranean, Breakfast & Brunch]",4.4,"[delivery, restaurant_reservation, pickup]",$$,1,1,...,0,0,0,0,0,0,False,True,False,False
2,16ZnHpuaaBt92XWeJHCC5A,Olio e Più,False,7330,"[Pizza, Italian, Cocktail Bars]",4.5,"[delivery, pickup]",$$$,1,1,...,0,0,0,0,0,0,False,False,True,False
3,qY1o1MhoRyN84RRhUJtvpQ,Her Name Is Han,False,2274,"[Korean, Breakfast & Brunch]",4.3,"[delivery, pickup]",$$,1,1,...,0,0,0,0,0,0,False,True,False,False
4,ysqgdbSrezXgVwER2kQWKA,Juliana's,False,2969,[Pizza],4.4,[delivery],$$,1,0,...,0,0,0,0,0,0,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,1dXX0xXyr99Syd_ZRXwhiA,Sushi Lin Upper West Side,False,22,"[Japanese, Sushi Bars, Seafood]",4.7,"[delivery, pickup]",NaN,1,1,...,0,0,0,0,0,0,False,False,False,False
230,X7PpqZZAMBhtmzeUvzfa5g,Musaafer,False,106,[Indian],4.2,[],$$$,0,0,...,0,0,0,0,0,0,False,False,True,False
231,hU1ajPmHi-kU6iNbowoEZg,Estiatorio Milos,False,410,"[Seafood, Greek, Mediterranean]",3.9,"[delivery, pickup]",$$$,1,1,...,0,0,0,0,0,0,False,False,True,False
232,6ARc7vXHWIyqndhQO81XVw,Or'esh,False,9,"[Mediterranean, Beer Bar, Cocktail Bars]",4.3,[],NaN,0,0,...,0,0,0,0,0,0,False,False,False,False
233,2RbBg1CIxBZAc2MQPdxkcA,Lillie's Victorian Establishment,False,1390,"[Bars, British, Gastropubs]",3.7,"[delivery, pickup]",$$,1,1,...,0,0,0,0,0,0,False,True,False,False

In [156]:
data["$"] = data["$"].astype(int)
data["$$"] = data["$$"].astype(int)
data["$$$"] = data["$$$"].astype(int)
data["$$$$"] = data["$$$$"].astype(int)

In [157]:
data

,id,name,is_closed,review_count,categories,rating,transactions,price,transactions_delivery,transactions_pickup,...,categories_Vegan,categories_Venezuelan,categories_Venues & Event Spaces,categories_Vietnamese,categories_Wine Bars,categories_Wraps,$,$$,$$$,$$$$
0,zRXMvxUX_rOliKZPpkWi_g,Valerie,False,1378,"[New American, Cocktail Bars]",4.2,[delivery],$$,1,0,...,0,0,0,0,0,0,0,1,0,0
1,hdiuRS9sVZSMReZm4oV5SA,Da Andrea - Greenwich Village,False,2744,"[Italian, Mediterranean, Breakfast & Brunch]",4.4,"[delivery, restaurant_reservation, pickup]",$$,1,1,...,0,0,0,0,0,0,0,1,0,0
2,16ZnHpuaaBt92XWeJHCC5A,Olio e Più,False,7330,"[Pizza, Italian, Cocktail Bars]",4.5,"[delivery, pickup]",$$$,1,1,...,0,0,0,0,0,0,0,0,1,0
3,qY1o1MhoRyN84RRhUJtvpQ,Her Name Is Han,False,2274,"[Korean, Breakfast & Brunch]",4.3,"[delivery, pickup]",$$,1,1,...,0,0,0,0,0,0,0,1,0,0
4,ysqgdbSrezXgVwER2kQWKA,Juliana's,False,2969,[Pizza],4.4,[delivery],$$,1,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,1dXX0xXyr99Syd_ZRXwhiA,Sushi Lin Upper West Side,False,22,"[Japanese, Sushi Bars, Seafood]",4.7,"[delivery, pickup]",NaN,1,1,...,0,0,0,0,0,0,0,0,0,0
230,X7PpqZZAMBhtmzeUvzfa5g,Musaafer,False,106,[Indian],4.2,[],$$$,0,0,...,0,0,0,0,0,0,0,0,1,0
231,hU1ajPmHi-kU6iNbowoEZg,Estiatorio Milos,False,410,"[Seafood, Greek, Mediterranean]",3.9,"[delivery, pickup]",$$$,1,1,...,0,0,0,0,0,0,0,0,1,0
232,6ARc7vXHWIyqndhQO81XVw,Or'esh,False,9,"[Mediterranean, Beer Bar, Cocktail Bars]",4.3,[],NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
233,2RbBg1CIxBZAc2MQPdxkcA,Lillie's Victorian Establishment,False,1390,"[Bars, British, Gastropubs]",3.7,"[delivery, pickup]",$$,1,1,...,0,0,0,0,0,0,0,1,0,0