In [86]:
import requests
from google.colab import userdata
import json
import pandas as pd

In [20]:
ta_data = pd.read_csv("ta_restaurants.csv")

Достаем самые популярные виды кухни из датасета trip advisor:

In [21]:
cuisine = ta_data["cuisine_type"].str.split(", ").explode().value_counts().head(50)
cuisine

cuisine_type
Американская               2082
Итальянская                1312
Открыто сейчас             1205
Азиатская                  1052
Бар                         877
Пицца                       815
Японская                    775
Бары и клубы                551
Средиземноморская           546
Китайская                   518
Мексиканская                416
Суши                        406
Французская                 373
Тайская                     360
Греческая                   340
Ирландская                  327
Кафе                        324
Фастфуд                     302
Стейк-хаус                  276
Морепродукты                273
Латиноамериканская          233
Сейчас закрыто              214
Индийская                   191
Паб                         186
Гастроном                   157
Европейская                 138
Испанская                   120
Закусочная                  114
Современная                 114
Карибская                   104
Здоровая                     97
Винный бар                   95
Десерты                      85
Корейская                    81
Ближневосточная              74
Международная                73
Барбекю                      60
Вьетнамская                  46
Ливанская                    44
Африканская                  43
Турецкая                     41
Перуанская                   38
Фьюжн                        37
Меню                         37
Южноамериканская             34
Израильская                  24
Откроется через 38 мин.      22
Каджунская и креольская      20
Бразильская                  18
Сегодня выходной             18
Name: count, dtype: int64

Собираем датасет из данных ресторанов с самыми популярным видами кухни:

In [74]:
import os

pupular_cuisines = ["tradamerican", "tradamerican", "italian", "japanese", "chinese", "mediterranean",  "mexican", "french", "thai", "greek", "irish"]

API_KEY = userdata.get("API_KEY")
fulldata = []


for cuisine in pupular_cuisines:
    page = requests.get(f"https://api.yelp.com/v3/businesses/search?location=New York City&categories={cuisine}&limit=50&offset={offset}",
                      headers={"accept": "application/json", "Authorization": f"Bearer {API_KEY}"})
    res = page.json()
    fulldata += res["businesses"]

In [75]:

data = pd.DataFrame(fulldata)
data

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,location,phone,display_phone,distance,business_hours,attributes,price
0,gZz9A8k8ORC_xl0aHxtY4w,monkey-bar-new-york-4,Monkey Bar,https://s3-media0.fl.yelpcdn.com/bphoto/bBVe73...,False,https://www.yelp.com/biz/monkey-bar-new-york-4...,459,"[{'alias': 'tradamerican', 'title': 'American'...",4.3,"{'latitude': 40.75998, 'longitude': -73.97313}",[],"{'address1': '60 E 54th St', 'address2': '', '...",+12124040365,(212) 404-0365,6297.867998,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht...",NaN
1,xt4sa64WOrpJvZBDPNPNYg,jacobs-pickles-new-york,Jacob's Pickles,https://s3-media0.fl.yelpcdn.com/bphoto/UOq1Bl...,False,https://www.yelp.com/biz/jacobs-pickles-new-yo...,5967,"[{'alias': 'comfortfood', 'title': 'Comfort Fo...",4.2,"{'latitude': 40.79113, 'longitude': -73.96908}","[pickup, delivery]","{'address1': '680 Columbus Ave', 'address2': '...",+12124705566,(212) 470-5566,9753.513207,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': Non...",$$
2,q1uIqB8PvyCCX8TajaRYBg,little-owl-new-york-3,Little Owl,https://s3-media0.fl.yelpcdn.com/bphoto/pgXH-Y...,False,https://www.yelp.com/biz/little-owl-new-york-3...,1548,"[{'alias': 'breakfast_brunch', 'title': 'Break...",4.2,"{'latitude': 40.73240001181511, 'longitude': -...","[pickup, delivery]","{'address1': '90 Bedford St', 'address2': None...",+12127414695,(212) 741-4695,3128.132245,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht...",$$$
3,ooYUO3Pq_qypc1NXFzeLYQ,city-vineyard-new-york-2,City Vineyard,https://s3-media0.fl.yelpcdn.com/bphoto/gn0e0y...,False,https://www.yelp.com/biz/city-vineyard-new-yor...,1282,"[{'alias': 'wine_bars', 'title': 'Wine Bars'},...",4.0,"{'latitude': 40.721365439014065, 'longitude': ...","[pickup, delivery]","{'address1': '233 West St', 'address2': '', 'a...",+16466778350,(646) 677-8350,2347.965269,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht...",$$$
4,V7lXZKBDzScDeGB8JmnzSA,katzs-delicatessen-new-york,Katz's Delicatessen,https://s3-media0.fl.yelpcdn.com/bphoto/4eB6Ir...,False,https://www.yelp.com/biz/katzs-delicatessen-ne...,16926,"[{'alias': 'delis', 'title': 'Delis'}, {'alias...",4.1,"{'latitude': 40.722208, 'longitude': -73.987433}","[pickup, delivery]","{'address1': '205 E Houston St', 'address2': '...",+12122542246,(212) 254-2246,1936.831370,"[{'open': [{'is_overnight': False, 'start': '0...","{'business_temp_closed': None, 'menu_url': 'ht...",$$
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,23NSOmpzzrJTfWmYk8Lp4A,lovely-day-new-york,Lovely Day,https://s3-media0.fl.yelpcdn.com/bphoto/IJmvGV...,False,https://www.yelp.com/biz/lovely-day-new-york?a...,421,"[{'alias': 'thai', 'title': 'Thai'}, {'alias':...",3.4,"{'latitude': 40.721774, 'longitude': -73.994275}","[delivery, pickup]","{'address1': '196 Elizabeth St', 'address2': '...",+12129253310,(212) 925-3310,1804.547000,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': Non...",$$
546,EZCXWw_OZL6JxZRgi2gMXA,noras-park-bench-cafe-brooklyn,Nora's Park Bench Cafe,https://s3-media0.fl.yelpcdn.com/bphoto/vJJ6en...,False,https://www.yelp.com/biz/noras-park-bench-cafe...,76,"[{'alias': 'irish', 'title': 'Irish'}, {'alias...",3.7,"{'latitude': 40.612267, 'longitude': -73.940975}",[pickup],"{'address1': '3019 Quentin Rd', 'address2': ''...",+17183760033,(718) 376-0033,11302.256028,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': Non...",$$
547,q_S2aqatVREvceTHI6c-lw,glenpatricks-pub-maspeth,Glenpatrick's Pub,https://s3-media0.fl.yelpcdn.com/bphoto/KOCznE...,False,https://www.yelp.com/biz/glenpatricks-pub-masp...,15,"[{'alias': 'sportsbars', 'title': 'Sports Bars...",4.4,"{'latitude': 40.7292, 'longitude': -73.89993}","[delivery, pickup]","{'address1': '53-73 65th Pl', 'address2': None...",+17184298334,(718) 429-8334,8369.214800,"[{'open': [{'is_overnight': True, 'start': '12...","{'business_temp_closed': None, 'menu_url': Non...",$
548,mn6JM5lHuSSsG9KSXck3ww,ulysses-new-york-2,Ulysses,https://s3-media0.fl.yelpcdn.com/bphoto/V6h_EH...,False,https://www.yelp.com/biz/ulysses-new-york-2?ad...,851,"[{'alias': 'pubs', 'title': 'Pubs'}, {'alias':...",3.2,"{'latitude': 40.70446500058935, 'longitude': -...",[delivery],"{'address1': '58 Stone St', 'address2': '', 'a...",+12124820400,(212) 482-0400,1332.913373,"[{'open': [{'is_overnight': True, 'start': '16...","{'business_temp_closed': None, 'menu_url': Non...",$$
549,_WVqaEFtX7KqCtqFQ1uVAA,mchales-bar-and-grill-new-york,McHale's Bar & Grill,https://s3-media0.fl.yelpcdn.com/bphoto/25hoKG...,False,https://www.yelp.com/biz/mchales-bar-and-grill...,333,"[{'alias': 'pubs', 'title': 'Pubs'}, {'alias':...",3.7,"{'latitude': 40.7628899, 'longitude': -73.984993}","[delivery, pickup]","{'address1': '251 W 51st St', 'address2': '', ...",+12129575138,(212) 957-5138,6419.634755,"[{'open': [{'is_overnight': True, 'start': '10...","{'business_temp_closed': None, 'menu_url': 'ht...",$$

In [76]:
data["id"].unique().shape

(487,)

In [77]:
data = data.drop_duplicates("id").reset_index()
data

,index,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,location,phone,display_phone,distance,business_hours,attributes,price
0,0,gZz9A8k8ORC_xl0aHxtY4w,monkey-bar-new-york-4,Monkey Bar,https://s3-media0.fl.yelpcdn.com/bphoto/bBVe73...,False,https://www.yelp.com/biz/monkey-bar-new-york-4...,459,"[{'alias': 'tradamerican', 'title': 'American'...",4.3,"{'latitude': 40.75998, 'longitude': -73.97313}",[],"{'address1': '60 E 54th St', 'address2': '', '...",+12124040365,(212) 404-0365,6297.867998,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht...",NaN
1,1,xt4sa64WOrpJvZBDPNPNYg,jacobs-pickles-new-york,Jacob's Pickles,https://s3-media0.fl.yelpcdn.com/bphoto/UOq1Bl...,False,https://www.yelp.com/biz/jacobs-pickles-new-yo...,5967,"[{'alias': 'comfortfood', 'title': 'Comfort Fo...",4.2,"{'latitude': 40.79113, 'longitude': -73.96908}","[pickup, delivery]","{'address1': '680 Columbus Ave', 'address2': '...",+12124705566,(212) 470-5566,9753.513207,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': Non...",$$
2,2,q1uIqB8PvyCCX8TajaRYBg,little-owl-new-york-3,Little Owl,https://s3-media0.fl.yelpcdn.com/bphoto/pgXH-Y...,False,https://www.yelp.com/biz/little-owl-new-york-3...,1548,"[{'alias': 'breakfast_brunch', 'title': 'Break...",4.2,"{'latitude': 40.73240001181511, 'longitude': -...","[pickup, delivery]","{'address1': '90 Bedford St', 'address2': None...",+12127414695,(212) 741-4695,3128.132245,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht...",$$$
3,3,ooYUO3Pq_qypc1NXFzeLYQ,city-vineyard-new-york-2,City Vineyard,https://s3-media0.fl.yelpcdn.com/bphoto/gn0e0y...,False,https://www.yelp.com/biz/city-vineyard-new-yor...,1282,"[{'alias': 'wine_bars', 'title': 'Wine Bars'},...",4.0,"{'latitude': 40.721365439014065, 'longitude': ...","[pickup, delivery]","{'address1': '233 West St', 'address2': '', 'a...",+16466778350,(646) 677-8350,2347.965269,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht...",$$$
4,4,V7lXZKBDzScDeGB8JmnzSA,katzs-delicatessen-new-york,Katz's Delicatessen,https://s3-media0.fl.yelpcdn.com/bphoto/4eB6Ir...,False,https://www.yelp.com/biz/katzs-delicatessen-ne...,16926,"[{'alias': 'delis', 'title': 'Delis'}, {'alias...",4.1,"{'latitude': 40.722208, 'longitude': -73.987433}","[pickup, delivery]","{'address1': '205 E Houston St', 'address2': '...",+12122542246,(212) 254-2246,1936.831370,"[{'open': [{'is_overnight': False, 'start': '0...","{'business_temp_closed': None, 'menu_url': 'ht...",$$
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482,545,23NSOmpzzrJTfWmYk8Lp4A,lovely-day-new-york,Lovely Day,https://s3-media0.fl.yelpcdn.com/bphoto/IJmvGV...,False,https://www.yelp.com/biz/lovely-day-new-york?a...,421,"[{'alias': 'thai', 'title': 'Thai'}, {'alias':...",3.4,"{'latitude': 40.721774, 'longitude': -73.994275}","[delivery, pickup]","{'address1': '196 Elizabeth St', 'address2': '...",+12129253310,(212) 925-3310,1804.547000,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': Non...",$$
483,546,EZCXWw_OZL6JxZRgi2gMXA,noras-park-bench-cafe-brooklyn,Nora's Park Bench Cafe,https://s3-media0.fl.yelpcdn.com/bphoto/vJJ6en...,False,https://www.yelp.com/biz/noras-park-bench-cafe...,76,"[{'alias': 'irish', 'title': 'Irish'}, {'alias...",3.7,"{'latitude': 40.612267, 'longitude': -73.940975}",[pickup],"{'address1': '3019 Quentin Rd', 'address2': ''...",+17183760033,(718) 376-0033,11302.256028,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': Non...",$$
484,547,q_S2aqatVREvceTHI6c-lw,glenpatricks-pub-maspeth,Glenpatrick's Pub,https://s3-media0.fl.yelpcdn.com/bphoto/KOCznE...,False,https://www.yelp.com/biz/glenpatricks-pub-masp...,15,"[{'alias': 'sportsbars', 'title': 'Sports Bars...",4.4,"{'latitude': 40.7292, 'longitude': -73.89993}","[delivery, pickup]","{'address1': '53-73 65th Pl', 'address2': None...",+17184298334,(718) 429-8334,8369.214800,"[{'open': [{'is_overnight': True, 'start': '12...","{'business_temp_closed': None, 'menu_url': Non...",$
485,548,mn6JM5lHuSSsG9KSXck3ww,ulysses-new-york-2,Ulysses,https://s3-media0.fl.yelpcdn.com/bphoto/V6h_EH...,False,https://www.yelp.com/biz/ulysses-new-york-2?ad...,851,"[{'alias': 'pubs', 'title': 'Pubs'}, {'alias':...",3.2,"{'latitude': 40.70446500058935, 'longitude': -...",[delivery],"{'address1': '58 Stone St', 'address2': '', 'a...",+12124820400,(212) 482-0400,1332.913373,"[{'open': [{'is_overnight': True, 'start': '16...","{'business_temp_closed': None, 'menu_url': Non...",$$
486,549,_WVqaEFtX7KqCtqFQ1uVAA,mchales-bar-and-grill-new-york,McHale's Bar & Grill,https://s3-media0.fl.yelpcdn.com/bphoto/25hoKG...,False,https://www.yelp.com/biz/mchales-bar-and-grill...,333,"[{'alias': 'pubs', 'title': 'Pubs'}, {'alias':...",3.7,"{'latitude': 40.7628899, 'longitude': -73.984993}","[delivery, pickup]","{'address1': '251 W 51st St', 'address2': '', ...",+12129575138,(212) 957-5138,6419.634755,"[{'open': [{'is_overnight': True, 'start': '10...","{'business_temp_closed': None, 'menu_url': 'ht...",$$

In [78]:
data = data[["id", "name", "is_closed", "review_count", "categories", "rating", "transactions", "price"]]

In [79]:
transactions_ohe = pd.get_dummies(data["transactions"].explode(), "transactions").groupby(level=0).sum()

In [80]:
data = pd.concat([data, transactions_ohe], axis=1)
data

,id,name,is_closed,review_count,categories,rating,transactions,price,transactions_delivery,transactions_pickup,transactions_restaurant_reservation
0,gZz9A8k8ORC_xl0aHxtY4w,Monkey Bar,False,459,"[{'alias': 'tradamerican', 'title': 'American'...",4.3,[],NaN,0,0,0
1,xt4sa64WOrpJvZBDPNPNYg,Jacob's Pickles,False,5967,"[{'alias': 'comfortfood', 'title': 'Comfort Fo...",4.2,"[pickup, delivery]",$$,1,1,0
2,q1uIqB8PvyCCX8TajaRYBg,Little Owl,False,1548,"[{'alias': 'breakfast_brunch', 'title': 'Break...",4.2,"[pickup, delivery]",$$$,1,1,0
3,ooYUO3Pq_qypc1NXFzeLYQ,City Vineyard,False,1282,"[{'alias': 'wine_bars', 'title': 'Wine Bars'},...",4.0,"[pickup, delivery]",$$$,1,1,0
4,V7lXZKBDzScDeGB8JmnzSA,Katz's Delicatessen,False,16926,"[{'alias': 'delis', 'title': 'Delis'}, {'alias...",4.1,"[pickup, delivery]",$$,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...
482,23NSOmpzzrJTfWmYk8Lp4A,Lovely Day,False,421,"[{'alias': 'thai', 'title': 'Thai'}, {'alias':...",3.4,"[delivery, pickup]",$$,1,1,0
483,EZCXWw_OZL6JxZRgi2gMXA,Nora's Park Bench Cafe,False,76,"[{'alias': 'irish', 'title': 'Irish'}, {'alias...",3.7,[pickup],$$,0,1,0
484,q_S2aqatVREvceTHI6c-lw,Glenpatrick's Pub,False,15,"[{'alias': 'sportsbars', 'title': 'Sports Bars...",4.4,"[delivery, pickup]",$,1,1,0
485,mn6JM5lHuSSsG9KSXck3ww,Ulysses,False,851,"[{'alias': 'pubs', 'title': 'Pubs'}, {'alias':...",3.2,[delivery],$$,1,0,0
486,_WVqaEFtX7KqCtqFQ1uVAA,McHale's Bar & Grill,False,333,"[{'alias': 'pubs', 'title': 'Pubs'}, {'alias':...",3.7,"[delivery, pickup]",$$,1,1,0

In [81]:
data["categories"] = data["categories"].apply(lambda x: [y["title"] for y in x])

In [82]:
categories_ohe = pd.get_dummies(data["categories"].explode(), "categories").groupby(level=0).sum()
data = pd.concat([data, categories_ohe], axis=1)

In [83]:
price_ohe = pd.get_dummies(data["price"])
data = pd.concat([data, price_ohe], axis=1)

In [84]:
data

,id,name,is_closed,review_count,categories,rating,transactions,price,transactions_delivery,transactions_pickup,...,categories_Vegan,categories_Vegetarian,categories_Venues & Event Spaces,categories_Vietnamese,categories_Wine Bars,categories_Wraps,$,$$,$$$,$$$$
0,gZz9A8k8ORC_xl0aHxtY4w,Monkey Bar,False,459,"[American, Bars]",4.3,[],NaN,0,0,...,0,0,0,0,0,0,False,False,False,False
1,xt4sa64WOrpJvZBDPNPNYg,Jacob's Pickles,False,5967,"[Comfort Food, Southern, American]",4.2,"[pickup, delivery]",$$,1,1,...,0,0,0,0,0,0,False,True,False,False
2,q1uIqB8PvyCCX8TajaRYBg,Little Owl,False,1548,"[Breakfast & Brunch, Mediterranean, American]",4.2,"[pickup, delivery]",$$$,1,1,...,0,0,0,0,0,0,False,False,True,False
3,ooYUO3Pq_qypc1NXFzeLYQ,City Vineyard,False,1282,"[Wine Bars, American, Venues & Event Spaces]",4.0,"[pickup, delivery]",$$$,1,1,...,0,0,1,0,1,0,False,False,True,False
4,V7lXZKBDzScDeGB8JmnzSA,Katz's Delicatessen,False,16926,"[Delis, American]",4.1,"[pickup, delivery]",$$,1,1,...,0,0,0,0,0,0,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482,23NSOmpzzrJTfWmYk8Lp4A,Lovely Day,False,421,"[Thai, Breakfast & Brunch, Irish]",3.4,"[delivery, pickup]",$$,1,1,...,0,0,0,0,0,0,False,True,False,False
483,EZCXWw_OZL6JxZRgi2gMXA,Nora's Park Bench Cafe,False,76,"[Irish, American]",3.7,[pickup],$$,0,1,...,0,0,0,0,0,0,False,True,False,False
484,q_S2aqatVREvceTHI6c-lw,Glenpatrick's Pub,False,15,"[Sports Bars, Irish Pub, Irish]",4.4,"[delivery, pickup]",$,1,1,...,0,0,0,0,0,0,True,False,False,False
485,mn6JM5lHuSSsG9KSXck3ww,Ulysses,False,851,"[Pubs, Irish, Sandwiches]",3.2,[delivery],$$,1,0,...,0,0,0,0,0,0,False,True,False,False
486,_WVqaEFtX7KqCtqFQ1uVAA,McHale's Bar & Grill,False,333,"[Pubs, American, Irish]",3.7,"[delivery, pickup]",$$,1,1,...,0,0,0,0,0,0,False,True,False,False

In [85]:
data["$"] = data["$"].astype(int)
data["$$"] = data["$$"].astype(int)
data["$$$"] = data["$$$"].astype(int)
data["$$$$"] = data["$$$$"].astype(int)

In [68]:
data

,id,name,is_closed,review_count,categories,rating,transactions,price,transactions_delivery,transactions_pickup,...,categories_Vegan,categories_Vegetarian,categories_Venues & Event Spaces,categories_Vietnamese,categories_Wine Bars,categories_Wraps,$,$$,$$$,$$$$
0,gZz9A8k8ORC_xl0aHxtY4w,Monkey Bar,False,459,"[American, Bars]",4.3,[],NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
1,xt4sa64WOrpJvZBDPNPNYg,Jacob's Pickles,False,5967,"[Comfort Food, Southern, American]",4.2,"[delivery, pickup]",$$,1,1,...,0,0,0,0,0,0,0,1,0,0
2,q1uIqB8PvyCCX8TajaRYBg,Little Owl,False,1548,"[Breakfast & Brunch, Mediterranean, American]",4.2,"[delivery, pickup]",$$$,1,1,...,0,0,0,0,0,0,0,0,1,0
3,ooYUO3Pq_qypc1NXFzeLYQ,City Vineyard,False,1282,"[Wine Bars, American, Venues & Event Spaces]",4.0,"[delivery, pickup]",$$$,1,1,...,0,0,1,0,1,0,0,0,1,0
4,V7lXZKBDzScDeGB8JmnzSA,Katz's Delicatessen,False,16926,"[Delis, American]",4.1,"[delivery, pickup]",$$,1,1,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482,23NSOmpzzrJTfWmYk8Lp4A,Lovely Day,False,421,"[Thai, Breakfast & Brunch, Irish]",3.4,"[pickup, delivery]",$$,1,1,...,0,0,0,0,0,0,0,1,0,0
483,EZCXWw_OZL6JxZRgi2gMXA,Nora's Park Bench Cafe,False,76,"[Irish, American]",3.7,[pickup],$$,0,1,...,0,0,0,0,0,0,0,1,0,0
484,mn6JM5lHuSSsG9KSXck3ww,Ulysses,False,851,"[Pubs, Irish, Sandwiches]",3.2,[delivery],$$,1,0,...,0,0,0,0,0,0,0,1,0,0
485,q_S2aqatVREvceTHI6c-lw,Glenpatrick's Pub,False,15,"[Sports Bars, Irish Pub, Irish]",4.4,"[pickup, delivery]",$,1,1,...,0,0,0,0,0,0,1,0,0,0
486,_WVqaEFtX7KqCtqFQ1uVAA,McHale's Bar & Grill,False,333,"[Pubs, American, Irish]",3.7,"[pickup, delivery]",$$,1,1,...,0,0,0,0,0,0,0,1,0,0